- src/rad/resources/schemas/common-1.0.0.yaml
- src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
- tests/conftest.py
- tests/test_manifest.py
- tests/test_schemas.py
- tox.ini
I discovered some bugs (and corresponding gaps in test coverage) when testing latest rad with roman_datamodels.  This PR fixes both.
> Fix tag URIs in metadata schemas and add test coverage

- src/rad/resources/schemas/rad_schema-1.0.0.yaml
Now that https://github.com/asdf-format/asdf/pull/987 has been merged, we can simplify the local references in this project's metaschema.
> Simplify metaschema references

- setup.cfg
asdf 2.8.0 is released, so we can use a real requirement here now.  Huzzah!
> Update asdf requirement to >= 2.8.0

- src/rad/resources/manifests/datamodels-1.0.yaml
- src/rad/resources/schemas/reference_files/gain-1.0.0.yaml
- src/rad/resources/schemas/reference_files/mask-1.0.0.yaml
- src/rad/resources/schemas/reference_files/readnoise-1.0.0.yaml
- src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
This PR is to add the remaining romancal reference modules: gain, mask, readnoise, and ref_common.
Tests: Fails due to dependency on dq support
Docs: Unneeded
Ticket: [#37]
> Added remaining romancal reference modules

- CHANGES.rst
- src/rad/resources/schemas/aperture-1.0.0.yaml
- src/rad/resources/schemas/basic-1.0.0.yaml
- src/rad/resources/schemas/ephemeris-1.0.0.yaml
- src/rad/resources/schemas/exposure-1.0.0.yaml
- src/rad/resources/schemas/guidestar-1.0.0.yaml
- src/rad/resources/schemas/observation-1.0.0.yaml
- src/rad/resources/schemas/pixelarea-1.0.0.yaml
- src/rad/resources/schemas/visit-1.0.0.yaml
This PR is to update the remaining schemas to the latest in RomanCAL. The affected schemas are: aperture, basic, ephemeris, exposure, guidestar, observation, pixelarea, and visit
Docs: Unneeded
Ticket: [#46]
> Updated remaining Nonreference RomanCal Schemas

- src/rad/resources/schemas/reference_files/dark-1.0.0.yaml
- src/rad/resources/schemas/reference_files/flat-1.0.0.yaml
- src/rad/resources/schemas/reference_files/gain-1.0.0.yaml
- src/rad/resources/schemas/reference_files/mask-1.0.0.yaml
- src/rad/resources/schemas/reference_files/readnoise-1.0.0.yaml
This prevents files from mixing and matching e.g. the FLAT reftype with the dark-1.0.0 tag.
> Validate each reference's specific reftype

- .github/workflows/release.yml
- scripts/insert_next_release
- scripts/set_release_date
This adds a workflow that tags and releases a new version of the package.  I'm trying to make releases low-friction so that we can do them every day if we need to.
The workflow may have bugs, but I'm not sure how to test it until we actually want a release.
> Add tag-and-release workflow

- CHANGES.rst
- src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
Much of what is in basic is irrelevant to reference files and should not be required in reference files. This PR removes that $ref of basic, and transfers the presumably required attributes directly to ref_common (as I understand it, this includes filename, file_date, telescope, and origin; if not, please comment).
Also removed is reftype since each reference file schema should include this attribute with a single enum value.
This closes #54
> Remove basic from ref_common as well as reftype

- src/rad/resources/schemas/cal_step-1.0.0.yaml
This adds other calbration steps to the schema. I intentionally did not add them to `required` as most of them are not implemented yet. Adding them now allows steps to use the attribute when they are developed.
> add other cal steps to schema

- CHANGES.rst
- src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
`PEDIGREE` is defined only as type string, however CRDs validates it against the following values:
`[INFLIGHT, GROUND, MODEL, DUMMY, SIMULATION]` and so files with arbitrary string values fail validation in CRDS.
This PR adds the enumeration to the schema.
> Add enumeration for pedigree values

- CHANGES.rst
- src/rad/resources/schemas/pixelarea-1.0.0.yaml
- src/rad/resources/schemas/wfi_image-1.0.0.yaml
This PR removes `pixelarea` and `var_flat` from the list of required attributes in the `wfi_image` schema.
The `wfi_image` schema is used for the first time with the output of ramp fitting. `pixelarea` and `var_flat` are not available at that time and the validation of the output of ramp_fitting fails.
> some attributes should not be required

- CHANGES.rst
- src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
The `pedestal` array in the optional output from ramp fitting, `ramp_fit_output`, represents the signal at zero exposure time for each pixel. Since Roman has one integration only I believe this array needs to be 2 dimensional.
> Pedestal array needs to be 2D

- CHANGES.rst
- src/rad/resources/schemas/exposure-1.0.0.yaml
Added boolean level0_compressed attribute keyword to exposure group to indicate if the level 0 data was compressed.
Closes #51
Resolves  [RAD-10](https://jira.stsci.edu/browse/RAD-10)
> RAD-10: Add attribute for compression in originating packets

- CHANGES.rst
- src/rad/resources/schemas/ramp-1.0.0.yaml
- src/rad/resources/schemas/wfi_image-1.0.0.yaml
- src/rad/resources/schemas/wfi_science_raw-1.0.0.yaml
Closes #107
Resolves [RAD-46](https://jira.stsci.edu/browse/RAD-46)
Changes to the schemas for the level 1 and 2 output files, as well as ramp model.
The level 1 file has a science data array that includes the border reference pixels, and a separate array for the amp 33 reference pixels.
The ramp model also has a data array that contains both science and border reference pixels, another for the amp 33 reference pixels, and four additional arrays for the original border reference pixels copied during the dq init step (plus four more for their dq arrays).
The level 2 file has a science data array only containing science pixles, 4 separate arrays for the top, bottom, left, and right original reference pixels (3d), four more for their dq arrays, and the amp33 array.
> RAD-46: changes to schemas for reference pixels

- CHANGES.rst
- setup.cfg
- src/rad/resources/schemas/photometry-1.0.0.yaml
- src/rad/resources/schemas/reference_files/wfi_img_photom-1.0.0.yaml
This is part of RCAL-111 - updating the `photometry` and `wfi_img_photom` schemas.
- Added "uncertainty" attributes
- - Changed the type to be either a Quantity (for imaging) or None (for spectral data)
> RCAL-111 Changes to photom schemas

- CHANGES.rst
- src/rad/resources/schemas/common-1.0.0.yaml
The `photometry` section is updated in the image file, in the last step of ELPP. 
Having it as a required property adds it to L1 files.
This PR makes it possible not to include it in L1 files. 
The alternative is to have it with dummy values.
> Remove 'photometry' from 'required' attributes in 'common'

- src/rad/resources/schemas/common-1.0.0.yaml
- src/rad/resources/schemas/photometry-1.0.0.yaml
- src/rad/resources/schemas/ramp-1.0.0.yaml
- src/rad/resources/schemas/reference_files/pixelarea-1.0.0.yaml
- src/rad/resources/schemas/reference_files/wfi_img_photom-1.0.0.yaml
- src/rad/resources/schemas/wfi_image-1.0.0.yaml
- tests/test_schemas.py
Changes:
- remove `photometry` from `common`
- change the datatype of `ramp.data` to float32
- change data types of attributes in pixelarea to `Quantity`
- remove `pixelarea` from Level2 schemas. The latest photometry algorithm specifies it won't be attached to files.
> tweaks to schemas

- CHANGES.rst
- src/rad/resources/schemas/reference_files/distortion-1.0.0.yaml
Removed exptype and p_keywords from Distortion schema.
> RAD-59: Remove exptype and p_keywords from Distortion Model

- src/rad/resources/schemas/aperture-1.0.0.yaml
Added an enumerated  list of Aperture names to the aperture schema to catch input errors. 
Closes RAD-60
> RAD-60 Add enum list of Aperture names to schema

- CHANGES.rst
- src/rad/resources/schemas/exposure-1.0.0.yaml
- src/rad/resources/schemas/observation-1.0.0.yaml
- src/rad/resources/schemas/reference_files/dark-1.0.0.yaml
Moved ma_table_name and ma_table_number from observation to exposure schemas.
> RAD-63: Move MA_Table Identifiers from Observation to Exposure Schemas

- CHANGES.rst
- src/rad/resources/schemas/exposure-1.0.0.yaml
Updated the attribute descriptions and reviewed the use of UTC. All times that are stored in non-UTC times need the other system. The MJD dates are used for multi-mission searches & the TDB times cannot be expressed in UTC in a meaningful why.
> Rad 51 Update the attribute descriptions in the exposure-1.0.0 schema

- CHANGES.rst
- setup.cfg
- src/rad/resources/schemas/observation-1.0.0.yaml
After review with INS it was decided to remove start_time and end_time from the observation schema since no use cases could be found and the origin of these times cannot be determined.
> RAD-52 After review remove observation.start_time and end_time

- CHANGES.rst
- src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
to avoid regenration of reference files
Follow up on #153 - reverted `ref_common.telescope` back to type `string` to avoid a last minute need to generate all reference files again.
> Keep "telescope" attribute in ref_common of type string 

- CHANGES.rst
- src/rad/resources/schemas/ref_file-1.0.0.yaml
Fix indentation issue, and change types from 'object' to string - reference file names don't need to be in a dictionary since their only property is their name.
> fix ref_file schema

- CHANGES.rst
- src/rad/resources/schemas/ref_file-1.0.0.yaml
This PR accomplishes two things:
1. Fixes the indentation of the ref_file.
2. Adds archive information to the CRDS keywords in the file.
Note: The archive information is fully accessible via the `schema_info` command (I have tested this). Moreover, the indentation exposed an issue with some of the test utilities in `roman_datamodels`, so this PR depends on spacetelescope/roman_datamodels#96 in order for all the tests to pass everywhere.
> Fix `ref_file` and and archive info to it

- CHANGES.rst
- src/rad/resources/manifests/datamodels-1.0.yaml
- src/rad/resources/schemas/unit/unit-1.0.0.yaml
Adds a schema and tag to support the non-VOUnits (`DN` and `electron`) that Roman will need to serialize in ASDF.
> RAD 99: Add schema to support Roman's non-VOUnit units.

- CHANGES.rst
- setup.cfg
- src/rad/resources/schemas/guidewindow-1.0.0.yaml
- src/rad/resources/schemas/ramp-1.0.0.yaml
- src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
- src/rad/resources/schemas/wfi_image-1.0.0.yaml
- src/rad/resources/schemas/wfi_science_raw-1.0.0.yaml
Add units to the schemas for science data quantities to specify allowed values.
Notes:
- ASDF library requirement update is to capture enum fix.
- Some objects have multiple units supported due to unit conversion (e.g. gain application, etc.) happening to model objects. (It is possible this may need expanding depending on how quantities are converted.)
- I made the units of crmag counts / s, but would it be better to use magnitude from astropy instead?
- I am less confident about the units of the intermediate ramp arrays (slope, yint, etc.).
> Rad 104: Enumerate Allowed Units for Science Data Quantities

- CHANGES.rst
- src/rad/resources/schemas/tagged_scalars/origin-1.0.0.yaml
- src/rad/resources/schemas/tagged_scalars/telescope-1.0.0.yaml
Fixes #155 
ASDF 2.14.2 fixes the bug causing #155 upstream. This PR re-enables `enum` for some tagged strings.
> Bugfix for `enum`

- src/rad/resources/manifests/datamodels-1.0.yaml
- src/rad/resources/schemas/associations-1.0.0.yaml
As the title says.. this is an initial take on a schema for associations. This was based on the JSON code at the bottom of this box. I am opening this in draft PR to facilitate conversation. There is a question of if we would like to validate JSON association files or not.
{
"asn_type": "image",
"asn_rule": "candidate_Asn_Lv2Image_i2d",
"version_id": null,
"code_version": "0.16.2.dev16+g640b0b79",
"degraded_status": "No known degraded exposures in association.",
"program": "00001",
"constraints": "DMSAttrConstraint({'name': 'program', 'sources': ['program'], 'value': '001'})\nConstraint_TargetAcq({'name': 'target_acq', 'value': 'target_acquisition'})\nDMSAttrConstraint({'name': 'science', 'DMSAttrConstraint({'name': 'asn_candidate', 'sources': ['asn_candidate'], 'value': …
> RAD-71: Initial Association datamodel schema support.

- .pre-commit-config.yaml
- CHANGES.rst
- docs/conf.py
- pyproject.toml
- scripts/insert_next_release
- scripts/set_release_date
- src/rad/__init__.py
- src/rad/integration.py
- tests/conftest.py
- tests/test_schemas.py
This PR applies some code formatters to `rad`. Namely:
- [`isort`](https://pycqa.github.io/isort/) to sort the imports.
- [`black`](https://black.readthedocs.io/en/stable/) to consistently format the code.
Note that this PR is based off #199, which should be merged first.
> Apply code formatters to `rad`

- .pre-commit-config.yaml
- CHANGES.rst
- docs/conf.py
- docs/index.rst
- pyproject.toml
- src/rad/resources/schemas/guidewindow-1.0.0.yaml
- src/rad/resources/schemas/reference_files/saturation-1.0.0.yaml
Applies the [`codespell`](https://github.com/codespell-project/codespell) to `rad` in order to automatically catch (and fix) most common spelling mistakes. Note that if `codespell` catches/fixes a word which is not misspelled, one can easily ignore the word by adding it to a new line under the `ignore-words-list` in the `pyproject.toml` file.
Note this is based on #201 so that it should be merged first.
> Apply `codespell` to `rad`

- CHANGES.rst
- src/rad/resources/schemas/tagged_scalars/file_date-1.0.0.yaml
- src/rad/resources/schemas/unit/unit-1.0.0.yaml
This PR moves root-level $ref properties to an allOf combiner.  The JSON Schema spec says that when $ref is present, all other properties in that object must be ignored:
https://datatracker.ietf.org/doc/html/draft-wright-json-schema-00#section-7
Which, when the $ref is at the top of the schema, includes critical properties such as "id".  The allOf combiner will have the same validation behavior but without the potentially nasty side effects.
This will be a warning in an upcoming version of asdf, and an error at some point after that.
**Checklist**
> Fix schemas with $ref  at root level

- CHANGES.rst
- src/rad/resources/schemas/cal_step-1.0.0.yaml
Resolves [RAD-116](https://jira.stsci.edu/browse/RAD-116)
Closes #223 
This PR temporarily makes the source detection step in cal_logs optional, to minimize regression test file recreation.
**Checklist**
> Temporarily make source detection optional in cal_logs.

- .github/CODEOWNERS
- CHANGES.rst
Closes #
This PR adds Jason to the list of reviewers for changes of the yaml files. 
**Checklist**
- [N/A] Updated relevant roman_datamodels utilities and tests
> Update codeowners file

- .github/workflows/changelog.yml
Given that #232 makes it explicit that we should be updating the changelog in each PR. This PR enforces that with a CI job.
Note if no changelog entry is desired, adding the `no-changelog-entry-needed` label will cause this job to pass.
**Checklist**
> Add changelog CI

- .github/CODEOWNERS
- .github/workflows/changelog.yml
- CHANGES.rst
The changelog CI currently really wants us to set milestones on our PRs. While adding milestones is technically best practice in this case, the reality of the actual development here is that we don't do this.
This PR turns off milestone checking in for our changelog.
**Checklist**
> Turn off milestone checks

- CHANGES.rst
- src/rad/resources/schemas/exposure-1.0.0.yaml
Resolves [RAD-120](https://jira.stsci.edu/browse/RAD-120)
Closes #
This PR adds read pattern to the exposure group.
**Checklist**
> RAD-120: Read Pattern

- CHANGES.rst
- src/rad/resources/schemas/reference_files/wfi_img_photom-1.0.0.yaml
Part of the reason why the issue leading to spacetelescope/roman_datamodels#170 was discovered was that end users were attempting to set the modified values as arrays. These values are expected to be scalar quantities with a specific unit. This PR adds additional conditions on these values to exactly specify them to be scalar quantities with a given unit.
**Checklist**
> Fully specify the `patternProperties` values for the `wfi_img_photom` schema

- CHANGES.rst
- src/rad/resources/schemas/observation-1.0.0.yaml
Resolves [RAD-119](https://jira.stsci.edu/browse/RAD-119)
Closes #251 
This PR updates the program to be a string to match association code.
**Checklist**
pytest tests/
=================================================================== test session starts ===================================================================
platform darwin -- Python 3.11.0, pytest-7.3.1, pluggy-1.0.0
rootdir: /Users/ddavis/src/Roman/rad
configfile: pyproject.toml
plugins: remotedata-0.4.0, hypothesis-6.75.1, asdf-2.15.0, mock-3.10.0, filter-subpackage-0.1.2, astropy-header-0.2.2, doctestplus-0.12.1, astropy-0.10.0, cov-4.0.0, ci-watson-0.6.1, openfiles-0.5.0, arraydiff-0.5.0
collected 397 items
tests/test_integration.py .......................................................... …
> RAD-119 Update program to be a string

- CHANGES.rst
- pyproject.toml
- src/rad/resources/schemas/reference_files/inverse_linearity-1.0.0.yaml
- tests/conftest.py
- tests/test_schemas.py
Resolves [RAD-126](https://jira.stsci.edu/browse/RAD-126)
Closes #271
This updates the `reftype` in the `inverse_linearity-1.0.0` schema to be compatible with CRDS. Additionally, it adds tests to the test suite to ensure future `reftype` values are CRDS compatible. 
**Checklist**
> Bugfix for `inverse_linearity-1.0.0` `reftype`

- CHANGES.rst
- src/rad/resources/schemas/associations-1.0.0.yaml
- src/rad/resources/schemas/guidewindow-1.0.0.yaml
- src/rad/resources/schemas/rad_schema-1.0.0.yaml
- src/rad/resources/schemas/ramp-1.0.0.yaml
- src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
- src/rad/resources/schemas/reference_files/dark-1.0.0.yaml
- src/rad/resources/schemas/reference_files/distortion-1.0.0.yaml
- src/rad/resources/schemas/reference_files/flat-1.0.0.yaml
- src/rad/resources/schemas/reference_files/gain-1.0.0.yaml
- src/rad/resources/schemas/reference_files/inverse_linearity-1.0.0.yaml
- src/rad/resources/schemas/reference_files/ipc-1.0.0.yaml
- src/rad/resources/schemas/reference_files/linearity-1.0.0.yaml
- src/rad/resources/schemas/reference_files/mask-1.0.0.yaml
- src/rad/resources/schemas/reference_files/pixelarea-1.0.0.yaml
- src/rad/resources/schemas/reference_files/readnoise-1.0.0.yaml
- src/rad/resources/schemas/reference_files/refpix-1.0.0.yaml
- src/rad/resources/schemas/reference_files/saturation-1.0.0.yaml
- src/rad/resources/schemas/reference_files/superbias-1.0.0.yaml
- src/rad/resources/schemas/reference_files/wfi_img_photom-1.0.0.yaml
- src/rad/resources/schemas/wfi_image-1.0.0.yaml
- src/rad/resources/schemas/wfi_mosaic-1.0.0.yaml
- src/rad/resources/schemas/wfi_science_raw-1.0.0.yaml
Currently, it can be slightly annoying to determine which schema represents the top-level schema for a given datamodel. This is because the datamodel name does not always precisely map back to the tag_uri, schema_uri, or schema name for the top-level schema, though in most cases it does but there is not a single consistent pattern among all such maps. For example
- The [`wfi_image-1.0.0` schema ](https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/wfi_image-1.0.0.yaml) maps to the [`ImageModel`](https://github.com/spacetelescope/roman_datamodels/blob/a271364d530e35c1b3580fdc414e417f44620c53/src/roman_datamodels/datamodels.py#L327-L328)
- While the [`ramp-1.0.0` schema](https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/ramp-1.0.0.yaml) maps to …
> Add entry to schemas to indicate Datamodel object

- CHANGES.rst
- src/rad/resources/manifests/datamodels-1.0.yaml
- src/rad/resources/schemas/msos_stack-1.0.0.yaml
Closes #274
This PR adds the datamodel schema requested in #274.
Tagging @lznakano, please let me know if this is acceptable for you.
**Checklist**
> SSC: L3 Datamodel for Stacked Image Data

- CHANGES.rst
- src/rad/resources/schemas/rad_schema-1.0.0.yaml
This uri fragment in rad_schema is invalid:
https://github.com/spacetelescope/rad/blob/97baad66112ee72ac31ac8da52b2a19e55efd401/src/rad/resources/schemas/rad_schema-1.0.0.yaml#L102
we were getting away with this because python jsonschema < 4.18 was less strict.
See https://github.com/asdf-format/asdf-standard/pull/373 for similar changes in asdf-standard.
**Checklist**
> fix uri fragment in rad_schema

- CHANGES.rst
- src/rad/resources/schemas/cal_step-1.0.0.yaml
PR #282 missed adding the `resample` step to`cal_step-1.0.0`. This PR adds the missing `resample` keyword. 
**Checklist**
> Add resample step to cal_step

- README.md
Related to [RCAL-613](https://jira.stsci.edu/browse/RCAL-613)
**Checklist**
> add installation instructions from romancal

- .github/workflows/changelog.yml
- README.md
Changelog check has moved upstream to Scientific Python. Trust me because I am the original author of the bot and I moved it during Scipy 2023 conference.
xref https://github.com/scientific-python/action-check-changelogfile/issues/4
**Checklist**
Your checklist is irrelevant here. This does not need a change log (otherwise it would be too meta).
> BOT: Changelog check has moved

- CHANGES.rst
- src/rad/resources/schemas/guidewindow-1.0.0.yaml
- src/rad/resources/schemas/rad_schema-1.0.0.yaml
- src/rad/resources/schemas/wfi_image-1.0.0.yaml
- src/rad/resources/schemas/wfi_mosaic-1.0.0.yaml
- src/rad/resources/schemas/wfi_science_raw-1.0.0.yaml
This PR adds an archive_meta keyword to the file-level schemas relevant to the archive. Currently, this keyword does not carry any information other than marking the schemas; however, discussions of how to structure this information are still on-going. This information will be added in follow-on pull requests.
**Checklist**
> Add archive_meta keyword

- CHANGES.rst
- src/rad/resources/schemas/cal_step-1.0.0.yaml
- src/rad/resources/schemas/ref_file-1.0.0.yaml
Closes #
This PR addresses an issue with archiving the reference files and populating the archive catalog. Previously the `archive_catalog` field was missing from the `ref_file` schema which caused the names of the files to not be populated in the database. In addition, there's a name collision because `reftype` is used  in `cal_step` and `ref_file`. While this is OK for the science files because they are under different tags, in the archive they go in the same database, and so for example `ref_file.dark` and `cal_step.dark` both map to `dark`. To resolve the name collision the archive destination names were changed: the ones in `cal_step` were prefixed with `s`, and the ones in `ref_file` were prefixed with `r`.
Note that these …
> Add archive_catalog field to ref_file

- CHANGES.rst
- src/rad/resources/schemas/cal_step-1.0.0.yaml
Resolves [RAD-128](https://jira.stsci.edu/browse/RAD-128)
Closes #287
This PR makes all the newly added cal_step steps required.
**Checklist**
> RAD-128 Require new cal_step values

- CHANGES.rst
- src/rad/resources/schemas/photometry-1.0.0.yaml
- src/rad/resources/schemas/reference_files/pixelarea-1.0.0.yaml
This PR adds enforcement of the units specified by descriptions of keywords, but which were not enforced by the schemas.
closes #268
**Checklist**
> Add missing unit enforcements

- CHANGES.rst
- src/rad/resources/schemas/reference_files/dark-1.0.0.yaml
Resolves [RAD-136](https://jira.stsci.edu/browse/RAD-136)
Closes #318 
This PR addresses adding slope and slope error to the dark reference file for use in the ramp fitting step. 
**Checklist**
> RAD-136 Add Slope and Error to Dark

- CHANGES.rst
- pyproject.toml
Resolves [RAD-135](https://jira.stsci.edu/browse/RAD-135)
Closes #317 
This PR updates the minimum supported python version to 3.9, matching the rest of the calibration pipeline. 
**Checklist**
> RAD-135 Updated minimum python version.

- CHANGES.rst
- src/rad/resources/schemas/tagged_scalars/origin-1.0.0.yaml
Resolves [RAD-133](https://jira.stsci.edu/browse/RAD-133)
Closes #315 
This PR expands the origin max character length in the archive catalog section.
**Checklist**
> RAD-133: Expanded origin db string length.

- CHANGES.rst
- src/rad/resources/schemas/wfi_science_raw-1.0.0.yaml
Resolves [RAD-132](https://jira.stsci.edu/browse/RAD-132)
Closes #304 
This PR adds an optional dq array to the Raw Science schema for use in labelling dropouts.
**Checklist**
> RAD-132: Added optional dq array to Science Raw

- CHANGES.rst
- src/rad/resources/schemas/exposure-1.0.0.yaml
- src/rad/resources/schemas/reference_files/dark-1.0.0.yaml
Closes #
This PR addresses schema changes needed for release 0.18.
- Adding new Dark keywords to the required list.
- Removed the truncated keyword from the GuideWindow table.
**Checklist**
> Misc Updates for release 0.18.

- CHANGES.rst
- src/rad/resources/schemas/wfi_image-1.0.0.yaml
- src/rad/resources/schemas/wfi_mosaic-1.0.0.yaml
- tests/test_schemas.py
Part of [RCAL-749](https://jira.stsci.edu/browse/RCAL-749)
Closes #
This PR addresses ...
**Checklist**
> Add WCS to schemas

- CHANGES.rst
- src/rad/resources/schemas/exposure-1.0.0.yaml
- src/rad/resources/schemas/guidewindow-1.0.0.yaml
- src/rad/resources/schemas/individual_image_meta-1.0.0.yaml
- src/rad/resources/schemas/msos_stack-1.0.0.yaml
- src/rad/resources/schemas/photometry-1.0.0.yaml
- src/rad/resources/schemas/ramp-1.0.0.yaml
- src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
- src/rad/resources/schemas/reference_files/dark-1.0.0.yaml
- src/rad/resources/schemas/reference_files/distortion-1.0.0.yaml
- src/rad/resources/schemas/reference_files/flat-1.0.0.yaml
- src/rad/resources/schemas/reference_files/gain-1.0.0.yaml
- src/rad/resources/schemas/reference_files/inverselinearity-1.0.0.yaml
- src/rad/resources/schemas/reference_files/ipc-1.0.0.yaml
- src/rad/resources/schemas/reference_files/linearity-1.0.0.yaml
- src/rad/resources/schemas/reference_files/mask-1.0.0.yaml
- src/rad/resources/schemas/reference_files/pixelarea-1.0.0.yaml
- src/rad/resources/schemas/reference_files/readnoise-1.0.0.yaml
- src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
- src/rad/resources/schemas/reference_files/refpix-1.0.0.yaml
- src/rad/resources/schemas/reference_files/saturation-1.0.0.yaml
- src/rad/resources/schemas/reference_files/superbias-1.0.0.yaml
- src/rad/resources/schemas/reference_files/wfi_img_photom-1.0.0.yaml
- src/rad/resources/schemas/visit-1.0.0.yaml
- src/rad/resources/schemas/wfi_image-1.0.0.yaml
- src/rad/resources/schemas/wfi_mosaic-1.0.0.yaml
- src/rad/resources/schemas/wfi_science_raw-1.0.0.yaml
- tests/test_schemas.py
This PR switches the `tag` keywords in the rad schemas to wildcard expressions for all tags outside of rad. For example:
https://github.com/spacetelescope/rad/blob/64cf407b88c1a369ca11d704f5af51347f7d9439/src/rad/resources/schemas/wfi_image-1.0.0.yaml#L34
is replaced by
```
tag: tag:stsci.edu:asdf/core/ndarray-1.*
```
The use of the wildcard `*` means that any `ndarray` tag with a version starting with `1.` will be considered valid.
This change is needed for asdf standard 1.6.0 (the current development version and upcoming stable version) which contains an increase in the `ndarray` tag version (from `1.0.0` to `1.1.0`). Many other tags will also see version changes to comply with 1.6.0 (including `time`, `quantity`, etc).
The type of failure that this PR will avoid can be seen in the …
> switch tag keywords for external tags to wildcards

- CHANGES.rst
- src/rad/resources/schemas/guidewindow-1.0.0.yaml
- src/rad/resources/schemas/msos_stack-1.0.0.yaml
- src/rad/resources/schemas/ramp-1.0.0.yaml
- src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
- src/rad/resources/schemas/reference_files/dark-1.0.0.yaml
- src/rad/resources/schemas/reference_files/flat-1.0.0.yaml
- src/rad/resources/schemas/reference_files/gain-1.0.0.yaml
- src/rad/resources/schemas/reference_files/inverselinearity-1.0.0.yaml
- src/rad/resources/schemas/reference_files/ipc-1.0.0.yaml
- src/rad/resources/schemas/reference_files/linearity-1.0.0.yaml
- src/rad/resources/schemas/reference_files/mask-1.0.0.yaml
- src/rad/resources/schemas/reference_files/pixelarea-1.0.0.yaml
- src/rad/resources/schemas/reference_files/readnoise-1.0.0.yaml
- src/rad/resources/schemas/reference_files/refpix-1.0.0.yaml
- src/rad/resources/schemas/reference_files/saturation-1.0.0.yaml
- src/rad/resources/schemas/reference_files/superbias-1.0.0.yaml
- src/rad/resources/schemas/wfi_image-1.0.0.yaml
- src/rad/resources/schemas/wfi_mosaic-1.0.0.yaml
- src/rad/resources/schemas/wfi_science_raw-1.0.0.yaml
- tests/test_schemas.py
for example RAD-1234: <Fix a bug> -->
Resolves [RAD-148](https://jira.stsci.edu/browse/RAD-148)
Closes #353
Require exact datatype for ndarrays. This means that ASDF will not attempt to make any type casting when saving files, so all types are explicitly defined in the romancal code.
**Checklist**
> RAD-148: Require exact datatypes for ndarrays

- CHANGES.rst
- src/rad/resources/schemas/aperture-1.0.0.yaml
- src/rad/resources/schemas/coordinates-1.0.0.yaml
- src/rad/resources/schemas/ephemeris-1.0.0.yaml
- src/rad/resources/schemas/exposure-1.0.0.yaml
- src/rad/resources/schemas/guidestar-1.0.0.yaml
- src/rad/resources/schemas/mosaic_basic-1.0.0.yaml
- src/rad/resources/schemas/mosaic_wcsinfo-1.0.0.yaml
- src/rad/resources/schemas/observation-1.0.0.yaml
- src/rad/resources/schemas/photometry-1.0.0.yaml
- src/rad/resources/schemas/pointing-1.0.0.yaml
- src/rad/resources/schemas/program-1.0.0.yaml
- src/rad/resources/schemas/ref_file-1.0.0.yaml
- src/rad/resources/schemas/tagged_scalars/calibration_software_version-1.0.0.yaml
- src/rad/resources/schemas/tagged_scalars/file_date-1.0.0.yaml
- src/rad/resources/schemas/tagged_scalars/filename-1.0.0.yaml
- src/rad/resources/schemas/tagged_scalars/model_type-1.0.0.yaml
- src/rad/resources/schemas/tagged_scalars/origin-1.0.0.yaml
- src/rad/resources/schemas/tagged_scalars/prd_software_version-1.0.0.yaml
- src/rad/resources/schemas/tagged_scalars/sdf_software_version-1.0.0.yaml
- src/rad/resources/schemas/tagged_scalars/telescope-1.0.0.yaml
- src/rad/resources/schemas/target-1.0.0.yaml
- src/rad/resources/schemas/velocity_aberration-1.0.0.yaml
- src/rad/resources/schemas/visit-1.0.0.yaml
- src/rad/resources/schemas/wcsinfo-1.0.0.yaml
- src/rad/resources/schemas/wfi_mode-1.0.0.yaml
Resolves [RAD-146](https://jira.stsci.edu/browse/RAD-146)
Closes #357
This PR addresses updating Product Table Names
**Checklist**
- [ x ] Schema changes discussed at RAD Review Board meeting
- [ x ] Added entry in `CHANGES.rst` under the corresponding subsection
> RAD-146: Update Product Table Names

- CHANGES.rst
- src/rad/resources/schemas/wfi_image-1.0.0.yaml
Resolves [RAD-158](https://jira.stsci.edu/browse/RAD-158)
Closes #388 
This PR changes the units of the variables within the Image Model schema. 
NOTE: no regression test link, because these changes require update to regression test files.
**Checklist**
> RAD-158: Changed image units.

- CHANGES.rst
- src/rad/resources/schemas/cal_step-1.0.0.yaml
Resolves [RAD-800](https://jira.stsci.edu/browse/RAD-800)
Related PRs:
- [roman_datamodel#332](https://github.com/spacetelescope/roman_datamodels/pull/332)
- [romancal#1160](https://github.com/spacetelescope/romancal/pull/1160)
This PR completes the schema setup for the new romancal FluxStep by adding it to the `cal_step` schema.
**Checklist**
> RCAL-800: Create the flux step schema

- CHANGES.rst
- src/rad/resources/schemas/resample-1.0.0.yaml
Resolves [RAD-139](https://jira.stsci.edu/browse/RAD-139)
Closes #340 
This PR adds the members keyword to the resample schema.
**Checklist**
> RAD-139: Add Members Keyword to Resample Schema

- CHANGES.rst
- docs/schemas.rst
- src/rad/resources/manifests/datamodels-1.0.yaml
- src/rad/resources/schemas/common-1.0.0.yaml
- src/rad/resources/schemas/ground_common-1.0.0.yaml
- src/rad/resources/schemas/l2_cal_step-1.0.0.yaml
- src/rad/resources/schemas/l3_cal_step-1.0.0.yaml
- src/rad/resources/schemas/wfi_mosaic-1.0.0.yaml
- src/rad/resources/schemas/wfi_science_raw-1.0.0.yaml
Resolves [RAD-149](https://jira.stsci.edu/browse/RAD-149)
Closes #363 
This PR splits the cal_step schema into L2 and L3 versions.
**Checklist**
> RAD-149: Split cal_step into L2 & L3

- CHANGES.rst
- src/rad/resources/schemas/exposure-1.0.0.yaml
- src/rad/resources/schemas/guidestar-1.0.0.yaml
Resolves [RAD-164](https://jira.stsci.edu/browse/RAD-164)
Closes #404 
This PR duplicates the keywords from `base_exposure` to `exposure` and similarly for `base_guidestar` and `guidestar`. This is a temporary fix until a more permanent resolution can be found (Issue #405).
**Checklist**
> RAD-164: Hotfix Of Exposure and Guidestar

- CHANGES.rst
- src/rad/resources/schemas/tvac_groundtest-1.0.0.yaml
Resolves [RAD-166](https://jira.stsci.edu/browse/RAD-166)
Closes #408 
This PR fixes an issue with schema_info not working on TVAC data.
**Checklist**
> RAD-166 Hotfix for TVAC Schema_Info Issue

- CHANGES.rst
- src/rad/resources/schemas/fps/groundtest-1.0.0.yaml
- src/rad/resources/schemas/tvac/groundtest-1.0.0.yaml
Resolves [RAD-169](https://jira.stsci.edu/browse/RAD-169)
Closes #416 
This PR removed the db entries for filename_l1a and filename_pnt5 in TVAC and FPS schemas
**Checklist**
> RAD-169: Drop filename_l1a and filename_pnt5 from database for TVAC and FPS schemas

- CHANGES.rst
- src/rad/resources/schemas/fps/groundtest-1.0.0.yaml
- src/rad/resources/schemas/tvac/groundtest-1.0.0.yaml
Resolves [RAD-168](https://jira.stsci.edu/browse/RAD-168)
Closes #417 
This PR removes filepath_level_pnt5 from TVAC/FPS database.
**Checklist**
> RAD-168: Drop filepath_level_pnt5 from TVAC/FPS database schema

- CHANGES.rst
- src/rad/resources/manifests/datamodels-1.0.yaml
- src/rad/resources/schemas/fps/statistics-1.0.0.yaml
- src/rad/resources/schemas/tvac/statistics-1.0.0.yaml
Resolves [RAD-171](https://jira.stsci.edu/browse/RAD-171)
Closes #412 
This PR adds a statistics schema to both FPS and TVAC.
**Checklist**
> RAD-171: Add statistics field to TVAC and FPS schemas

- CHANGES.rst
- src/rad/resources/schemas/l2_cal_step-1.0.0.yaml
- src/rad/resources/schemas/l3_cal_step-1.0.0.yaml
Resolves [RAD-162](https://jira.stsci.edu/browse/RAD-162)
Closes #400 
This PR removes reference file and guidewindow db tables from cal_step schemas.
**Checklist**
> RAD-162: Remove GuideWindow and Ref tables from cal_step

- changes/446.doc.rst
- docs/ground_tests.rst
- docs/reference_files.rst
- docs/schemas.rst
Updates schema docs to:
- remove mention of "File schemas"
- add a one sentence description
- add links to asdf schema docs and roman_datamodels docs
Link to updated docs: https://rad--446.org.readthedocs.build/en/446/schemas.html
Only a docs change so no downstream tests will be run.
Closes #427
</details
> Clarify docs headers

- docs/ground_tests.rst
The schema list in the ground tests docs isn't rendering:
https://rad.readthedocs.io/en/latest/ground_tests.html
This PR fixes the formatting to allow them to render:
https://rad--447.org.readthedocs.build/en/447/ground_tests.html
Closes: https://github.com/spacetelescope/rad/issues/444
</details
> fix ground test docs schema list

- .github/workflows/build.yml
- .github/workflows/changelog.yml
- .github/workflows/ci.yml
- .github/workflows/ci_cron.yml
- .github/workflows/release.yml
As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)
> MNT: Use hash for Action workflow versions and update if needed

- changes/462.feature.rst
- src/rad/resources/schemas/wfi_mosaic-1.0.0.yaml
Currently var_flat is optional in individual exposures and required in mosaics.  This doesn't make very much sense, since var_flat cannot be populated in mosaics if it doesn't exist in the individual exposures.  This PR removes var_flat from the list of required attributes in the mosaic metadata.
> Make var_flat optional in L3 files.

- changes/485.removal.rst
- src/rad/resources/schemas/photometry-1.0.0.yaml
- src/rad/resources/schemas/ramp-1.0.0.yaml
- src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml
- src/rad/resources/schemas/sky_background-1.0.0.yaml
- src/rad/resources/schemas/wfi_image-1.0.0.yaml
- src/rad/resources/schemas/wfi_mosaic-1.0.0.yaml
- src/rad/resources/schemas/wfi_science_raw-1.0.0.yaml
Resolves [RCAL-911](https://jira.stsci.edu/browse/RCAL-911)
Resolves [RCAL-932](https://jira.stsci.edu/browse/RCAL-932)
This PR modifies several files so that units are not used anymore.
The information about units is still retained in the RAD schema.
<details><summary>news fragment change types...</summary>
- ``changes/485.removal.rst``: Remove units from rad schema.
</details>
> RCAL-911 & 932: remove units from MOS and ELP pipelines.

- .github/workflows/ci.yml
- changes/468.feature.rst
This PR adds python 3.13 to the CI. As it shows no errors the changelog says we support python 3.13
</details
> test with python 3.13

- .pre-commit-config.yaml
- changes/466.misc.rst
- src/rad/resources/schemas/cal_logs-1.0.0.yaml
- src/rad/resources/schemas/l2_cal_step-1.0.0.yaml
Resolves [RAD-83](https://jira.stsci.edu/browse/RAD-83)
Closes #173 
This PR updates ``cal_step`` and ``cal_log`` schemas
</details
> RAD-83: Update Cal_step and Cal_log schemas

- changes/469.misc.rst
- src/rad/resources/schemas/ephemeris-1.0.0.yaml
Resolves [RAD-85](https://jira.stsci.edu/browse/RAD-85)
Closes #175 
This PR updates ephemeris descriptions
</details
> RAD-85: Update/Add ephemeris descriptions

- changes/475.misc.rst
- src/rad/resources/schemas/pointing-1.0.0.yaml
Resolves [RAD-89](https://jira.stsci.edu/browse/RAD-89)
Closes #178 
This PR updates the pointing schema
</details
> RAD-89: Update/Add pointing descriptions

- changes/476.misc.rst
- src/rad/resources/schemas/velocity_aberration-1.0.0.yaml
Resolves [RAD-91](https://jira.stsci.edu/browse/RAD-91)
Closes #190 
This PR updates velocity_aberration descriptions and keywords
</details
> RAD-91: Updates velocity_aberration descriptions

- .pre-commit-config.yaml
- changes/477.misc.rst
- src/rad/resources/schemas/wcsinfo-1.0.0.yaml
Resolves [RAD-93](https://jira.stsci.edu/browse/RAD-93)
Closes #181 
This PR updates wcs keywords and attribute information
</details
> RAD-93: Update wcs attribute information

- .pre-commit-config.yaml
- changes/478.misc.rst
- src/rad/resources/schemas/exposure-1.0.0.yaml
- src/rad/resources/schemas/exposure_type-1.0.0.yaml
- src/rad/resources/schemas/program-1.0.0.yaml
Resolves [RAD-86](https://jira.stsci.edu/browse/RAD-86)
Closes #176
This PR updates exposure and program attributes information
</details
> RAD-86: Update exposure and program attributes information

- changes/479.misc.rst
- src/rad/resources/schemas/ref_file-1.0.0.yaml
Resolves [RAD-90](https://jira.stsci.edu/browse/RAD-90)
Closes #185 
This PR updates ref_file descriptions
</details
> RAD-90: Update ref_file descriptions

- .pre-commit-config.yaml
- changes/480.misc.rst
- src/rad/resources/schemas/observation-1.0.0.yaml
Resolves [RAD-88](https://jira.stsci.edu/browse/RAD-88)
Closes #187 
This PR updates observation descriptions
</details
> RAD-88: Update observation descriptions

- changes/498.misc.rst
- src/rad/resources/schemas/wcsinfo-1.0.0.yaml
Resolves [RAD-177](https://jira.stsci.edu/browse/RAD-177)
Closes #426 
This PR adds alternate WFI aperture names to match both the SIAF and legacy names.
</details
> RAD-177: Update aperture names

- changes/506.misc.rst
- src/rad/resources/schemas/ref_file-1.0.0.yaml
Resolves [RAD-1234](https://jira.stsci.edu/browse/RAD-nnnn)
Closes #502
This PR adds CRDS and reference steps required lists.
</details
> RAD-502: CRDS Keywords Not Required 

- changes/510.misc.rst
- pyproject.toml
Now that the release is made we can remove the upper pin for asdf. This should help to fix the "test_with_nightly" run (although other pins might need to be removed in romancal):
https://github.com/spacetelescope/RegressionTests/actions/runs/11865364654/job/33070520465#step:14:190
</details
> remove upper pin for asdf

- .github/workflows/ci_cron.yml
- pyproject.toml
- tox.ini
This is what `tox` recommends. It also allows this `tox` to be compatible with using `tox-uv`.
</details
> Use the list_dependencies_command instead of pip freeze

- .github/workflows/ci.yml
- tox.ini
closes #263
This PR adds downstream testing of `roman_datamodels`.
</details
> Add roman_datamodels testing job

- .pre-commit-config.yaml
- docs/conf.py
- pyproject.toml
- scripts/insert_next_release.py
- scripts/set_release_date.py
- src/rad/integration.py
- tests/test_integration.py
- tests/test_schemas.py
This PR cleans up the linting in RAD, so that ruff is used over other tools performing the same function.
</details
> Clean up linting

- .github/workflows/ci.yml
- .github/workflows/ci_cron.yml
- changes/520.misc.rst
- docs/conf.py
- pyproject.toml
This PR bumps min python to 3.11 per [SPEC 0](https://scientific-python.org/specs/spec-0000/#support-window). `astropy` 7 has already made this bump.
</details
> Per SPEC 0, bump min python to 3.11

- changes/516.misc.rst
- src/rad/resources/schemas/reference_files/abvegaoffset-1.0.0.yaml
- src/rad/resources/schemas/reference_files/apcorr-1.0.0.yaml
Resolves [RAD-189](https://jira.stsci.edu/browse/RAD-189)
Closes #488 
This PR adds null values to allowed APCORR and ABVEGAOFFSET keyword values.
</details
> RAD-189: APCORR and ABVEGAOFFSET optional nulls

- changes/525.bugfix.rst
- src/rad/resources/schemas/exposure-1.0.0.yaml
- src/rad/resources/schemas/fps/exposure-1.0.0.yaml
- src/rad/resources/schemas/fps/guidestar-1.0.0.yaml
- src/rad/resources/schemas/fps/wfi_mode-1.0.0.yaml
- src/rad/resources/schemas/guidestar-1.0.0.yaml
- src/rad/resources/schemas/guidewindow-1.0.0.yaml
- src/rad/resources/schemas/mosaic_basic-1.0.0.yaml
- src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
- src/rad/resources/schemas/reference_files/ref_exposure_type-1.0.0.yaml
- src/rad/resources/schemas/reference_files/ref_optical_element-1.0.0.yaml
- src/rad/resources/schemas/segmentation_map-1.0.0.yaml
- src/rad/resources/schemas/tvac/exposure-1.0.0.yaml
- src/rad/resources/schemas/tvac/guidestar-1.0.0.yaml
- src/rad/resources/schemas/tvac/wfi_mode-1.0.0.yaml
- src/rad/resources/schemas/wfi_mode-1.0.0.yaml
- tests/test_schemas.py
Including a `$ref` key in a schema mapping/object/dict comes with the requirement that other members of that mapping are ignored. See https://datatracker.ietf.org/doc/html/draft-pbryan-zyp-json-ref-03#section-3
This PR updates the RAD schemas nesting `$ref`s in `allOf` combiners when the mapping contains other items and adds a test to verify the changes.
Romancal regtests all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/12260132209 …
> move refs under allOfs where required

- changes/490.feature.rst
- src/rad/resources/schemas/reference_files/dark-1.0.0.yaml
- src/rad/resources/schemas/reference_files/distortion-1.0.0.yaml
- src/rad/resources/schemas/reference_files/gain-1.0.0.yaml
- src/rad/resources/schemas/reference_files/inverselinearity-1.0.0.yaml
- src/rad/resources/schemas/reference_files/linearity-1.0.0.yaml
- src/rad/resources/schemas/reference_files/pixelarea-1.0.0.yaml
- src/rad/resources/schemas/reference_files/readnoise-1.0.0.yaml
- src/rad/resources/schemas/reference_files/refpix-1.0.0.yaml
- src/rad/resources/schemas/reference_files/saturation-1.0.0.yaml
- src/rad/resources/schemas/reference_files/wfi_img_photom-1.0.0.yaml
- tests/test_schemas.py
Resolves [RAD-192](https://jira.stsci.edu/browse/RAD-192)
Closes #489
This PR removes the units from the reference files.
</details
> Remove units from the ref files

- pyproject.toml
- tox.ini
The tox for `oldestdeps` test was broken. This PR fixes that.
</details
> Bugfix the oldestdeps job

- changes/505.feature.rst
- src/rad/resources/schemas/ref_file-1.0.0.yaml
- tests/test_schemas.py
Closes #502
Closes #503
In order to walk the schemas to find `archive_catalog` information, a valid `AsdfFile` object must exist satisfying those schemas. Thus in order to discover this metadata, all those properties must be present meaning that they must be required by the schemas.
This PR adds a test to check that `archive_catalog` (and `sdf`) force the keyword to be required. Moreover, this PR fixes all the failures detected by this process.
</details
> Fix issues with `archive_catalog` marked keywords not being required

- changes/542.bugfix.rst
- src/rad/resources/schemas/reference_files/apcorr-1.0.0.yaml
The asdf datatype validator raises an exception instead of yielding leading to incorrect validation failure for the `anyOf` schema combiner in the apcorr ref file schema (xref: https://github.com/asdf-format/asdf/issues/1903).
This PR works around the issue (until an asdf fix can be made and released) by reordering the `anyOf` to check for `None` first (when this succeeds the remainder of the `anyOf` will not be evaluated avoiding the asdf bug).
</details
> reorder anyOf in apcorr schema to work around asdf bug

- .github/workflows/ci.yml
- tox.ini
Add romancal unit tests to the CI (similar to the roman_datamodels tests).
</details
> add romancal downstream testing to ci

- changes/572.doc.rst
- docs/versioning.rst
Update versioning docs to reflect the 16 Jan 2025 RAD meeting where it was discussed that:
> Versioning only required for changes that affect the datamodel based on the schema. Accordingly, database, RSDP, other archive_catalog field changes, etc. will not require new versions.
Link to updated docs: https://rad--572.org.readthedocs.build/en/572/versioning.html#non-versioned-changes
</details
> update versioning docs

- changes/564.feature.rst
- docs/schemas.rst
- src/rad/resources/manifests/datamodels-1.0.yaml
- src/rad/resources/manifests/datamodels-1.1.0.yaml
- src/rad/resources/schemas/wfi_wcs-1.0.0.yaml
- tests/test_schemas.py
Resolves [RAD-206](https://jira.stsci.edu/browse/RAD-206)
WIP [RCAL-1025](https://jira.stsci.edu/browse/RCAL-1025)
This PR creates the new schema `WfiWcs`. This schema defines the new ELP product output as defined in RCAL-1025. This schema represents the WCS determined for each L2 output from ELP. If the `tweakreg` step is executed successfully, this WCS represents the GAIA-aligned solution. The intent of this file is to document this calculated WCS and, if desired, be applied back to the L1 product.
- …
> RAD-206: Define new schema WfiWcs

- changes/574.misc.rst
- src/rad/resources/manifests/datamodels-1.1.0.yaml
- src/rad/resources/schemas/common-1.1.0.yaml
- src/rad/resources/schemas/ephemeris-1.1.0.yaml
- src/rad/resources/schemas/exposure-1.1.0.yaml
- src/rad/resources/schemas/guidestar-1.1.0.yaml
- src/rad/resources/schemas/guidewindow_modes-1.0.0.yaml
- src/rad/resources/schemas/l2_cal_step-1.0.0.yaml
- src/rad/resources/schemas/l2_cal_step-1.1.0.yaml
- src/rad/resources/schemas/l3_cal_step-1.1.0.yaml
- src/rad/resources/schemas/mosaic_segmentation_map-1.1.0.yaml
- src/rad/resources/schemas/mosaic_source_catalog-1.1.0.yaml
- src/rad/resources/schemas/pointing-1.1.0.yaml
- src/rad/resources/schemas/program-1.1.0.yaml
- src/rad/resources/schemas/ramp-1.1.0.yaml
- src/rad/resources/schemas/segmentation_map-1.1.0.yaml
- src/rad/resources/schemas/visit-1.1.0.yaml
- src/rad/resources/schemas/wcsinfo-1.1.0.yaml
- src/rad/resources/schemas/wfi_image-1.1.0.yaml
- src/rad/resources/schemas/wfi_mode-1.0.0.yaml
- src/rad/resources/schemas/wfi_mosaic-1.1.0.yaml
- src/rad/resources/schemas/wfi_science_raw-1.1.0.yaml
- src/rad/resources/schemas/wfi_wcs-1.0.0.yaml
Resolves [RAD-207](https://jira.stsci.edu/browse/RAD-207)
Closes #561 #568 
This PR adjusts several RTB directed L1 & L2 metadata schema changes.
</details
> RAD-207: Update L1 and L2 Schema

- changes/603.feature.rst
- pyproject.toml
Closes #405
The fixes for #405 have been in place with an ASDF release (4.1.0) for awhile. This PR bumps the min ASDF to that version to ensure that the `schema_info` issue is fixed.
</details
> Bump the asdf version to 4.1.0 to fix schema_info issue

- changes/612.feature.rst
- latest/datamodels.yaml
- src/rad/resources/manifests/datamodels-1.2.0.yaml
- src/rad/resources/manifests/datamodels-1.3.0.yaml
- tests/conftest.py
- tests/test_integration.py
- tests/test_latest.py
- tests/test_manifest.py
- tests/test_schemas.py
- tests/test_versioning.py
This PR bumps the datamodels manifest so that we can start making changes for the next version.
</details
> Bump the datamodels to v1.3.0 now that rad 0.25 is released

- .github/workflows/ci.yml
Something has changed in `romancal` which is causing the CI job to fail even though the upstream packages (`roman_datamodels` and `romancal`) do not seem to have CI problems. This PR attempts to resolve that issue.
</details
> Fix romancal CI job

- changes/573.feature.rst
- latest/wfi_mosaic.yaml
Resolves [RAD-968](https://jira.stsci.edu/browse/RAD-968)
This PR adds a new attribute, `var_sky`, to the mosaic schema.
This PR supports changes in romancal's [PR#1691](https://github.com/spacetelescope/romancal/pull/1691).
All the regression tests are passing:
- https://github.com/spacetelescope/RegressionTests/actions/runs/14365098776
</details
> RCAL-968: add var_sky to mosaic schema.

- scripts/helper/_manager.py
The manager was not populating the sub directories without the user interacting directly with that subdirectory in the app widget. This fixes that by forcing it to walk the entire thing.
</details
> Small bugfix for the rad resource helper

- changes/636.feature.rst
- latest/exposure_type.yaml
- latest/reference_files/ref_exposure_type.yaml
Reverts spacetelescope/rad#636
This caused several regtest failures for the scheduled run:
https://github.com/spacetelescope/RegressionTests/actions/runs/16208770638
Until we have a fix for this I vote for reverting.
> Revert "Remove deprecated exposure types from schema definitions"

- changes/655.feature.rst
- latest/SSC/CGI/keywords/cgi_ancillary.yaml
- latest/SSC/CGI/keywords/cgi_common.yaml
- latest/SSC/CGI/keywords/cgi_exposure.yaml
- latest/SSC/CGI/keywords/cgi_mechanism_named_settings.yaml
- latest/SSC/CGI/keywords/cgi_pointing.yaml
- latest/SSC/CGI/keywords/cgi_region.yaml
- latest/SSC/CGI/keywords/cgi_states.yaml
- latest/SSC/CGI/keywords/cgi_visit.yaml
- latest/SSC/ssc_basic.yaml
This PR fills in some of the placeholders for the CGI schema archive destinations.
</details
> Updates to  archive destinations for CGI schemas

- scripts/helper/_app.py
- scripts/helper/_edit.py
- scripts/helper/_frozen.py
- scripts/helper/_manager.py
- scripts/helper/_resource.py
This PR addresses a couple of minor bugs I have discovered with the helper script. 
</details
> Bugfix for creating new resources with rad script

- changes/686.misc.rst
- pyproject.toml
- src/rad/integration.py
- tests/conftest.py
- tests/test_integration.py
- tests/test_schemas.py
- tests/test_versioning.py
Resolves [RAD-220](https://jira.stsci.edu/browse/RAD-220)
Closes #672
This PR removes the versioning testing from the SSC schemas and removes ASDF's direct packaging of those schemas. I currently does not remove any of the additional testing such as the `required` testing for now as I think we need to carefully review which of those unit tests we wish to apply.
</details
> RAD-220: Remove versioning and ASDF packaging of SSC schemas

- CONTRIBUTING.rst
- changes/682.doc.rst
Resolves [RAD-219](https://jira.stsci.edu/browse/RAD-219)
Closes #670
Update the contributors file with more detailed instructions for how to contribute to RAD.
</details
> RAD-219 Update contributors file

- changes/685.bugfix.rst
- src/rad/resources/schemas/fps-1.0.0.yaml
- tests/test_versioning.py
Resolves [RAD-221](https://jira.stsci.edu/browse/RAD-221)
Closes #679
After careful investigation of the FPS_SAMPLE files for RITA, I have determined that it is "safe" to adjust the FPS schema so that it does in fact reference the fps statistics schema without fear of breaking the existing files that RITA has. This PR makes that change to the schema.
</details
> RAD-221: Add statistics to the FPS schema

- pyproject.toml
Similar to https://github.com/spacetelescope/roman_datamodels/pull/563
This configures setuptools-scm to be aware of our release branches when determining a version. This should remove the need for development tags.
</details
> tell setuptools-scm we use release branches

- README.md
I noticed that some of the readme badges were broken this PR fixes that.
</details
> Fix the readme badges
