spacetelescope/rad

src/rad/resources/schemas/aperture-1.0.0.yaml, src/rad/resources/schemas/cal_step-1.0.0.yaml, src/rad/resources/schemas/common-1.0.0.yaml, src/rad/resources/schemas/coordinates-1.0.0.yaml, src/rad/resources/schemas/ephemeris-1.0.0.yaml, src/rad/resources/schemas/exposure-1.0.0.yaml, src/rad/resources/schemas/guidestar-1.0.0.yaml, src/rad/resources/schemas/observation-1.0.0.yaml, src/rad/resources/schemas/photometry-1.0.0.yaml, src/rad/resources/schemas/pointing-1.0.0.yaml, src/rad/resources/schemas/program-1.0.0.yaml, src/rad/resources/schemas/target-1.0.0.yaml, src/rad/resources/schemas/velocity_aberration-1.0.0.yaml, src/rad/resources/schemas/visit-1.0.0.yaml, src/rad/resources/schemas/wcsinfo-1.0.0.yaml, src/rad/resources/schemas/wfi_mode-1.0.0.yaml
This is just my best guess.  For archive catalog I used the datamodelname but something I added the section.
sdf - I made lots of guesses.
=> RAD-1 Add sdf and archive_catalog sections

.gitignore, src/rad/resources/schemas/observation-1.0.0.yaml, src/rad/resources/schemas/reference_files/flat-1.0.0.yaml
A small fix was needed for the observation schema (name mismatch between the properties and the required properties and propertyOrder, a fix to the flat field schema, and adding a file to .gitignore
=> Minor schema corrections

src/rad/resources/manifests/datamodels-1.0.yaml
I thought I fixed this in the previous PR but no such luck...
=> Update extension URI

src/rad/resources/schemas/reference_files/flat-1.0.0.yaml, src/rad/resources/schemas/wfi_science_raw-1.0.0.yaml, tests/test_schemas.py
Having flowStyle in the wrong place causes asdf to raise an error, so I thought we'd better have a check for that.  I also updated the ndarray properties to use the special-purpose validators that asdf offers for those.
=> Improve flowStyle and propertyOrder tests, update ndarray validators

tests/test_manifest.py
The final version of this schema has a fully three-part version.
=> Update manifest schema URI

CHANGES.rst, src/rad/resources/manifests/datamodels-1.0.yaml, src/rad/resources/schemas/reference_files/dark-1.0.0.yaml
This PR is to add the dark schema and update the flat reference yaml.
Docs: Unneeded
Ticket: [#35]
=> Added dark and updated flat schemas.

CHANGES.rst, src/rad/resources/manifests/datamodels-1.0.yaml, src/rad/resources/schemas/dq_def-1.0.0.yaml
This PR is to add DQ definition schema.
Docs: Unneeded
Ticket: #32
=> Added dq support.

CHANGES.rst, src/rad/resources/manifests/datamodels-1.0.yaml, src/rad/resources/schemas/variance-1.0.0.yaml
This PR is to add variance schema.
Docs: Unneeded
Ticket: [#38]
=> Added variance support.

CHANGES.rst, src/rad/resources/manifests/datamodels-1.0.yaml, src/rad/resources/schemas/reference_files/wfi_img_photom-1.0.0.yaml, tests/test_schemas.py
This PR is to add photom.
Docs: Unneeded
Ticket: [#34]
=> Added photom support.

CHANGES.rst, src/rad/resources/manifests/datamodels-1.0.yaml, src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml, src/rad/resources/schemas/rampfitoutput-1.0.0.yaml, src/rad/resources/schemas/reference_files/wfi_img_photom-1.0.0.yaml
Ticket to fix a couple inaccuracies and omissions in rampfitoutput and wfi_img_photom.
=> Fixed a few issues that cropped up from testing (Rampfitoutput & WFI_ing_photom).

CHANGES.rst, src/rad/resources/schemas/wfi_science_raw-1.0.0.yaml
This ticket adjusts the number of dimensions in the data variable in Science Raw to match the contents of the file.
=> RAD-26 Adjust dimensions of WFI Science Raw data.

CHANGES.rst, src/rad/resources/schemas/reference_files/wfi_img_photom-1.0.0.yaml, src/rad/resources/schemas/wfi_mode-1.0.0.yaml
This was done months ago, but got lost when its PR was split up into smaller PRs.
=> Changed Engineering to F213 in optical_element.

CHANGES.rst, src/rad/resources/manifests/datamodels-1.0.yaml, src/rad/resources/schemas/reference_files/saturation-1.0.0.yaml
Added schema for saturation reference file support.
=> Added saturation reference file support.

CHANGES.rst, src/rad/resources/manifests/datamodels-1.0.yaml, src/rad/resources/schemas/reference_files/pixelarea-1.0.0.yaml
Adding support for pixel area reference files.
=> RAD-29 Adding support for pixel area reference files.

CHANGES.rst, src/rad/resources/manifests/datamodels-1.0.yaml, src/rad/resources/schemas/reference_files/superbias-1.0.0.yaml
Added support for super-bias reference files.
=> RAD-31 Added support for super-bias reference files.

CHANGES.rst, src/rad/resources/schemas/reference_files/dark-1.0.0.yaml, src/rad/resources/schemas/reference_files/flat-1.0.0.yaml, src/rad/resources/schemas/reference_files/pixelarea-1.0.0.yaml, src/rad/resources/schemas/reference_files/ref_optical_element-1.0.0.yaml, src/rad/resources/schemas/wfi_mode-1.0.0.yaml, src/rad/resources/schemas/wfi_optical_element-1.0.0.yaml, tests/test_schemas.py
Added optical_element to appropriate reference file schemas. 
Added ma_table_name to dark schema. 
Adjusted pixelarea schema imports.
=> RAD-39 Add Optical_Element to Reference File Schemas

src/rad/resources/schemas/exposure-1.0.0.yaml, src/rad/resources/schemas/rad_schema-1.0.0.yaml, src/rad/resources/schemas/visit-1.0.0.yaml
Changing archive_catalog bit datatype fields to nchar(1).
=> RAD-42 Change bit fields to nchar(1)

.github/workflows/ci.yml, tox.ini
@eslavich Any idea what causes the error?
=> Test with Python 3.10

CHANGES.rst, src/rad/resources/schemas/cal_step-1.0.0.yaml
Set all calsteps to required in cal logs.
=> RAD-43: Add Remaining Calsteps to Required

CHANGES.rst, src/rad/resources/schemas/guidestar-1.0.0.yaml
Added guide window mode data. I've left the CGI off the mode list for now since it is not clear what we would do with it in that attribute.
=> RAD-45 Add Guide window modes to guide star schema

CHANGES.rst, src/rad/resources/schemas/reference_files/dark-1.0.0.yaml
Updated dark schema to include group keywords from exposure.
=> RAD-49 Updated dark schema to include group keywords from exposure.

CHANGES.rst, src/rad/resources/schemas/exposure-1.0.0.yaml, src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml, src/rad/resources/schemas/wfi_detector-1.0.0.yaml, src/rad/resources/schemas/wfi_mode-1.0.0.yaml
Moved detector list to new file for importing to both data and reference schemas.
=> RAD-54: Add Instrument and Detector to Reference Schemas

CHANGES.rst, src/rad/resources/manifests/datamodels-1.0.yaml, src/rad/resources/schemas/reference_files/distortion-1.0.0.yaml, src/rad/resources/schemas/wfi_detector-1.0.0.yaml
Added support for Distortion reference files. 
Tweaked schema for WFI detector list.
=> RAD-55: Create Distortion Schema

CHANGES.rst, src/rad/resources/schemas/cal_step-1.0.0.yaml
Added photom keyword attribute to cal_step schema.
=> RAD-61: Adding Photom to Cal_Step

CHANGES.rst, src/rad/resources/schemas/observation-1.0.0.yaml, src/rad/resources/schemas/reference_files/dark-1.0.0.yaml
Added ma_table_number to observation and dark schemas.
=> RAD-57: Add ma_table_number to the schema

CHANGES.rst
Update Changes.rst for release 0.11.0
=> Updates for CHANGES.rst for release 0.11.0

CHANGES.rst
Update CHANGES.rst for release 0.12.0
=> Update CHANGES.rst for release 0.12.0

src/rad/resources/schemas/ref_file-1.0.0.yaml
I am going to merge this without waiting for a review.
=> fix typo in ref_file

CHANGES.rst, src/rad/resources/schemas/ramp-1.0.0.yaml
Changed the dimensionality of the err variable in ramp.
=> RAD-65: Update error array in ramp-1.0.0.yaml

CHANGES.rst, src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml
As per [this comment.](https://github.com/spacetelescope/rad/pull/158#issuecomment-1198697257)
Pipeline test passing locally.
=> Use anyOf with telescope

CHANGES.rst, src/rad/resources/schemas/target-1.0.0.yaml
Deleted source_type_apt from target-1.0.0.yaml
=> RAD-98:Delete source_type_apt from target-1.0.0.yaml

CHANGES.rst, src/rad/resources/schemas/observation-1.0.0.yaml
Adjust activity identifier in observation schema to better reflect potential values.
=> RAD-78: Update observation activity description

CHANGES.rst, src/rad/resources/schemas/ephemeris-1.0.0.yaml
Changed SDF "origin" in ephemeris-1.0.0.yaml to use definitve/predicted ephemeris
=> RAD-97: Change SDF "origin" in ephemeris-1.0.0.yaml

CHANGES.rst, src/rad/resources/schemas/guidestar-1.0.0.yaml, src/rad/resources/schemas/guidewindow-1.0.0.yaml
Ticket to change the variable type of x/y start/stop/size in guidewindow schema. Added those keywords to the guidestar schema as well.
=> RAD-108: Correcting Guidewindow Start Stop

CHANGES.rst, src/rad/resources/manifests/datamodels-1.0.yaml, src/rad/resources/schemas/reference_files/ipc-1.0.0.yaml
Ticket to add the interpixel capacitance correction schema.
=> RAD-100: Write a schema for IPC reference file

CHANGES.rst, src/rad/resources/manifests/datamodels-1.0.yaml, src/rad/resources/schemas/reference_files/inverse_linearity-1.0.0.yaml
Created inverse non-linearity schema.
=> RAD-107: Create Inverse Non-Linearity Schema

.github/pull_request_template.md, CHANGES.rst
Adding a Pull Request Template.
=> RAD-114: PR Template

.github/CODEOWNERS, CHANGES.rst
Closes #227
This PR updates the code owner file to add the database team (Kim DuPrie & Jason Brookens) to review any changes to the yaml files. 
**Checklist**
- [N/A] Schema changes discussed at RAD Review Board meeting
- [N/A] Updated relevant roman_datamodels utilities and tests
=> Update reviewers for Code Owners file

CHANGES.rst, src/rad/resources/schemas/associations-1.0.0.yaml, src/rad/resources/schemas/exposure-1.0.0.yaml, src/rad/resources/schemas/guidewindow-1.0.0.yaml, src/rad/resources/schemas/ramp-1.0.0.yaml, src/rad/resources/schemas/ramp_fit_output-1.0.0.yaml, src/rad/resources/schemas/reference_files/dark-1.0.0.yaml, src/rad/resources/schemas/reference_files/distortion-1.0.0.yaml, src/rad/resources/schemas/reference_files/ref_common-1.0.0.yaml, src/rad/resources/schemas/reference_files/ref_exposure_type-1.0.0.yaml, src/rad/resources/schemas/reference_files/ref_optical_element-1.0.0.yaml, src/rad/resources/schemas/wfi_science_raw-1.0.0.yaml
[RAD-125](https://jira.stsci.edu/browse/RAD-125)
Closes #260
I have been noting some discrepancies, which @PaulHuwe turned into issue #260. I have since found a couple of other ones. This pull request resolves all the ones I have found so far.
**Checklist**
=> RAD-125: Fix minor discrepancies

CHANGES.rst
This PR addresses document updates for release 0.16.0.
**Checklist**
=> Release 0.16.0 document updates.

CHANGES.rst, src/rad/resources/schemas/cal_step-1.0.0.yaml
This PR adds additional steps to the cal_step schema
**Checklist**
=> Update `cal_step` for new Roman steps

.github/workflows/ci_cron.yml, tox.ini
This PR fixes the cov job broken by the new tox release.
**Checklist**
=> Fix cov job

.github/workflows/ci.yml, .github/workflows/ci_cron.yml
Add python 3.12 dev testing
**Checklist**
=> Update CI for python 3.12 dev testing

CHANGES.rst, src/rad/resources/schemas/reference_files/dark-1.0.0.yaml
This PR is an addendum to RAD-136 in order to remove the `err` array. 
**Checklist**
=> Rad 136 dark slope err

CHANGES.rst, src/rad/resources/schemas/tagged_scalars/calibration_software_version-1.0.0.yaml, src/rad/resources/schemas/tagged_scalars/file_date-1.0.0.yaml, src/rad/resources/schemas/tagged_scalars/filename-1.0.0.yaml, src/rad/resources/schemas/tagged_scalars/model_type-1.0.0.yaml, src/rad/resources/schemas/tagged_scalars/origin-1.0.0.yaml, src/rad/resources/schemas/tagged_scalars/prd_software_version-1.0.0.yaml, src/rad/resources/schemas/tagged_scalars/sdf_software_version-1.0.0.yaml, src/rad/resources/schemas/tagged_scalars/telescope-1.0.0.yaml
Resolves [RAD-134](https://jira.stsci.edu/browse/RAD-134)
Closes #316 
This PR adds GuideWindow db table to Basic tagged scalars.
**Checklist**
=> RAD-134: Added GuideWindow db table to Basic tagged scalars.

README.md, tox.ini
This PR fixes the devdeps job.
**Checklist**
=> Fix devdeps

CHANGES.rst, docs/index.rst, docs/reference_files.rst, docs/schemas.rst
Resolves [RAD-154](https://jira.stsci.edu/browse/RAD-154)
Closes #381 
This PR adds newly added schemas to the documentation. 
It also rearranges the list of schemas placing the science products at the top.
**Checklist**
=> RAD-154: Improve documentation

CHANGES.rst, src/rad/resources/schemas/mosaic_basic-1.0.0.yaml, src/rad/resources/schemas/tagged_scalars/calibration_software_version-1.0.0.yaml, src/rad/resources/schemas/tagged_scalars/file_date-1.0.0.yaml, src/rad/resources/schemas/tagged_scalars/model_type-1.0.0.yaml, src/rad/resources/schemas/tagged_scalars/origin-1.0.0.yaml, src/rad/resources/schemas/tagged_scalars/prd_software_version-1.0.0.yaml, src/rad/resources/schemas/tagged_scalars/sdf_software_version-1.0.0.yaml, src/rad/resources/schemas/wfi_mosaic-1.0.0.yaml
Resolves [RAD-155](https://jira.stsci.edu/browse/RAD-155)
Closes #383 
Closes #384 
This PR adds the `basic` schema to `WfiMosaic` and removes the duplicate attributes from `wfi_basic`.
**Checklist**
=> RAD-155: Move basic out of  mosaic_basic

.github/workflows/ci.yml, .github/workflows/ci_cron.yml, .readthedocs.yml, pyproject.toml
resolves [SCSB-145](https://jira.stsci.edu/browse/SCSB-145)
propagate Astropy's deprecation of Python 3.9 to downstream packages
> [!NOTE]
> this PR was generated automatically by ``batchpr`` :robot:
=> [SCSB-145] require Python 3.10

CHANGES.rst, src/rad/resources/schemas/fps/cal_step-1.0.0.yaml, src/rad/resources/schemas/fps/exposure-1.0.0.yaml, src/rad/resources/schemas/fps/groundtest-1.0.0.yaml, src/rad/resources/schemas/fps/guidestar-1.0.0.yaml, src/rad/resources/schemas/fps/ref_file-1.0.0.yaml, src/rad/resources/schemas/fps/tagged_scalars/calibration_software_version-1.0.0.yaml, src/rad/resources/schemas/fps/tagged_scalars/file_date-1.0.0.yaml, src/rad/resources/schemas/fps/tagged_scalars/filename-1.0.0.yaml, src/rad/resources/schemas/fps/tagged_scalars/model_type-1.0.0.yaml, src/rad/resources/schemas/fps/tagged_scalars/origin-1.0.0.yaml, src/rad/resources/schemas/fps/tagged_scalars/prd_software_version-1.0.0.yaml, src/rad/resources/schemas/fps/tagged_scalars/sdf_software_version-1.0.0.yaml, src/rad/resources/schemas/fps/tagged_scalars/telescope-1.0.0.yaml, src/rad/resources/schemas/fps/wfi_mode-1.0.0.yaml, src/rad/resources/schemas/tvac/cal_step-1.0.0.yaml, src/rad/resources/schemas/tvac/exposure-1.0.0.yaml, src/rad/resources/schemas/tvac/guidestar-1.0.0.yaml, src/rad/resources/schemas/tvac/ref_file-1.0.0.yaml, src/rad/resources/schemas/tvac/tagged_scalars/calibration_software_version-1.0.0.yaml, src/rad/resources/schemas/tvac/tagged_scalars/file_date-1.0.0.yaml, src/rad/resources/schemas/tvac/tagged_scalars/filename-1.0.0.yaml, src/rad/resources/schemas/tvac/tagged_scalars/model_type-1.0.0.yaml, src/rad/resources/schemas/tvac/tagged_scalars/origin-1.0.0.yaml, src/rad/resources/schemas/tvac/tagged_scalars/prd_software_version-1.0.0.yaml, src/rad/resources/schemas/tvac/tagged_scalars/sdf_software_version-1.0.0.yaml, src/rad/resources/schemas/tvac/tagged_scalars/telescope-1.0.0.yaml, src/rad/resources/schemas/tvac/wfi_mode-1.0.0.yaml
Resolves [RAD-170](https://jira.stsci.edu/browse/RAD-170)
Closes #415 
This PR fixes the TVAC & FPS archive catalog destinations.
**Checklist**
=> RAD-170: Fix TVAC & RPS Archive Cat Destinations

changes/458.doc.rst, src/rad/resources/schemas/ref_file-1.0.0.yaml
Resolves [RAD-176](https://jira.stsci.edu/browse/RAD-176)
Closes #431 #457 
This PR adds ref_file entry for reference pixel subtraction reference file.
</details
=> RAD-176: Add ref_file entry for reference pixel subtraction reference file

changes/467.misc.rst, src/rad/resources/schemas/coordinates-1.0.0.yaml
Resolves [RAD-84](https://jira.stsci.edu/browse/RAD-84)
Closes #174
This PR updates the coordinate schema descriptions.
</details
=> RAD-84: Update coordinate schema descriptions

changes/471.misc.rst, src/rad/resources/schemas/guidestar-1.0.0.yaml, src/rad/resources/schemas/guidewindow_modes-1.0.0.yaml, src/rad/resources/schemas/photometry-1.0.0.yaml, src/rad/resources/schemas/wfi_mode-1.0.0.yaml
Resolves [RAD-181](https://jira.stsci.edu/browse/RAD-181)
Closes #470 
This PR update guide_star, instrument, and photometry schemas.
</details
=> RAD-181: Update guide_star, instrument, and photometry schemas

changes/544.misc.rst, src/rad/resources/schemas/exposure-1.0.0.yaml, src/rad/resources/schemas/program-1.0.0.yaml, src/rad/resources/schemas/visit-1.0.0.yaml, src/rad/resources/schemas/wfi_mode-1.0.0.yaml
Resolves [RAD-202](https://jira.stsci.edu/browse/RAD-202)
Closes #543 
This PR changes some RSDP origin values.
</details
=> RAD-202: add origin definitions for RSDP

docs/reference_files.rst
This PR adds the recently defined reference file schemas to the RTD docs
- abvegaoffset
- apcorr
- epsf
- skycells
This PR addresses ...
</details
=> Add newly defined reference file schemas to documentation

changes/553.feature.rst, docs/reference_files.rst, src/rad/resources/manifests/datamodels-1.0.yaml, src/rad/resources/schemas/reference_files/matable-1.0.0.yaml, tests/test_schemas.py
Resolves [RAD-180](https://jira.stsci.edu/browse/RAD-180)
Closes #461 
This PR adds an MA Table reference schema. 
</details
=> RAD-180 MA Table Reference Schema

changes/580.feature.rst, src/rad/resources/manifests/datamodels-1.1.0.yaml, src/rad/resources/schemas/l1_face_guidewindow-1.0.0.yaml
Resolves [RAD-204](https://jira.stsci.edu/browse/RAD-204)
Closes #
This PR adds L1 Average FACE Guide Window File Schema.
</details
=> RAD-204: L1 Average FACE Guide Window File Schema

docs/schemas.rst
Resolves [RAD-209](https://jira.stsci.edu/browse/RAD-209)
Closes #575 
This PR updates the schema generation list for documentation.
</details
=> RAD-209: Update schema versions docs

changes/621.bugfix.rst, latest/l1_detector_guidewindow.yaml, latest/l1_face_guidewindow.yaml
Someone noticed a typo in the `wsm_edge_used` title field. I went ahead and corrected the fields in "latest".
=> Update wsm_edge_used title

.pre-commit-config.yaml
uses a common `.pre-commit-config.yaml` with other repositories in pipeline dependencies
As of the creation of this PR, checks that would change any files are commented out.
</details
=> consistent `pre-commit` config

changes/692.feature.rst, latest/datamodels.yaml, latest/msos_stack.yaml, src/rad/resources/schemas/msos_stack-1.3.0.yaml, src/rad/resources/schemas/msos_stack-1.4.0.yaml
Closes #635 
This PR addresses the additional extension on the MSOS Stacked image (L3) for the PSF images per detector. Please let Lijun Zhang (MSOS developer) review the changes and make further suggestions. Thank you!
- [ o ] Does this PR change any schema files?
</details
=> Add psf to msos_stack.yaml

CONTRIBUTING.rst, README.md
This PR adds a note kindly requesting that people open their own PRs on RAD when they want specific targeted changes made.
</details
=> Add note to contributor guide
